"""Full Stage-2 (30 data point) verification of the size-independent
``--platform-asm`` kernels for the three contest problems.

Each problem's 10 data-point shapes are generated on the fly, the emitted ``.s``
is executed by the tiny RV32IMF interpreter from ``test_platform_kernels.py``,
and the result is compared against a NumPy reference. This is the end-to-end
check that one size-independent ``.s`` per problem covers every data point.

The platform's Stage-2 problems are **float32 / rv32imf**:

- ``fwht``:  ``a0 = x[N]``, ``a1 = out[N]``, ``a2 = N``
- ``winograd`` (direct-conv baseline): ``a0`` points at
  ``[batch,H,W,Cin,Cout,K] ++ feat(NHWC) ++ weights(OIHW)``; ``a1`` is NCHW
- ``spmm``:  ``a0`` points at ``[M,K,N,nnz] ++ row_ptr ++ col_idx ++ values ++ B``

Skipped by default: the largest SpMM points take tens of seconds each under the
pure-Python interpreter (~3 min total). Run explicitly with::

    SCRATCHV_PLATFORM_STAGE2=1 PYTHONPATH=. python3.11 \
        -m pytest tests/test_platform_stage2.py -q
"""

import contextlib
import importlib.util
import io
import os
import pathlib

import numpy as np
import pytest

pytestmark = pytest.mark.skipif(
    os.environ.get("SCRATCHV_PLATFORM_STAGE2") != "1",
    reason="set SCRATCHV_PLATFORM_STAGE2=1 to run the full 30-point "
           "platform-kernel check (~3 min)",
)

_here = pathlib.Path(__file__).resolve().parent
_spec = importlib.util.spec_from_file_location(
    "_tpk", _here / "test_platform_kernels.py")
_tpk = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_tpk)

_f32 = np.float32
_MASK = 0xFFFFFFFF

# ── Stage-2 data-point specs ───────────────────────────────────────────────
FWHT = [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
# (batch, H, W, Cin, Cout, K) — the platform's 内测比赛2 winograd data points.
CONV = [(1, 8, 8, 3, 8, 3), (1, 8, 8, 4, 16, 3), (1, 8, 8, 5, 8, 5),
        (2, 8, 8, 3, 8, 3), (1, 6, 6, 16, 16, 3), (1, 5, 5, 24, 24, 3),
        (1, 8, 8, 10, 8, 5), (1, 5, 5, 32, 16, 3), (1, 6, 6, 24, 16, 3),
        (2, 6, 6, 16, 12, 3)]
# (M, K, N, density) — shape only; structure is generated by _spmm_model.
SPMM = [(128, 128, 1, 0.90), (256, 256, 1, 0.95), (128, 128, 4, 0.85),
        (512, 256, 1, 0.98), (1000, 64, 4, 0.99), (120, 300, 1, 0.90),
        (100, 100, 8, 0.80), (96, 512, 1, 0.95), (64, 64, 8, 0.70),
        (64, 64, 16, 0.50)]


def _emit(model, tmp_path):
    import onnx
    from scratchv.standalone.onnx_to_riscv_standalone import (
        ONNXModel, CNNRISCVGenerator, MemoryPlan, emit_platform_asm)
    path = tmp_path / "m.onnx"
    onnx.save(model, str(path))
    m = ONNXModel.from_file(str(path))
    mem = MemoryPlan()
    for vi in m.inputs:
        n = 1
        for d in m.get_shape(vi.name):
            n *= d
        mem.alloc_workspace(vi.name, n)
    wd = mem.layout_weights(m.initializers)
    gen = CNNRISCVGenerator(m, mem)
    with contextlib.redirect_stdout(io.StringIO()):
        gen.generate()
    return emit_platform_asm(gen, wd, m)


def _run(asm, regs_init, mem, max_steps=400_000_000):
    prog, labels = _tpk._parse(asm)
    regs = [0] * 32
    for i, v in regs_init.items():
        regs[i] = v
    _tpk._run(prog, labels, regs, mem, max_steps=max_steps)


# ── builders ──────────────────────────────────────────────────────────────
def _fwht_model(n):
    from onnx import TensorProto, helper
    x = helper.make_tensor_value_info("X", TensorProto.FLOAT, [1, n])
    y = helper.make_tensor_value_info("Y", TensorProto.FLOAT, [1, n])
    node = helper.make_node("Fwht", ["X"], ["Y"], domain="org.scratchv")
    return helper.make_model(
        helper.make_graph([node], "f", [x], [y]),
        opset_imports=[helper.make_opsetid("org.scratchv", 1),
                       helper.make_opsetid("", 13)])


def _conv_model(batch, H, W, Cin, Cout, K):
    from onnx import TensorProto, helper
    x = helper.make_tensor_value_info("x", TensorProto.FLOAT, [batch, Cin, H, W])
    y = helper.make_tensor_value_info("y", TensorProto.FLOAT, [batch, Cout, H, W])
    rng = np.random.default_rng(abs(hash((batch, H, W, Cin, Cout, K))) % 2**32)
    wt = helper.make_tensor(
        "w", TensorProto.FLOAT, [Cout, Cin, K, K],
        rng.normal(0, 0.3, size=Cout * Cin * K * K).astype(np.float32).ravel().tolist())
    pad = K // 2
    node = helper.make_node("Conv", ["x", "w"], ["y"],
                            pads=[pad, pad, pad, pad])
    return helper.make_model(
        helper.make_graph([node], "c", [x], [y], [wt]),
        opset_imports=[helper.make_opsetid("", 13)])


def _spmm_model(M, K, N, dens, seed):
    from onnx import TensorProto, helper
    rng = np.random.default_rng(seed)
    mask = rng.random((M, K)) < (1.0 - dens)
    A = (mask * rng.uniform(-0.9, 0.9, (M, K))).astype(np.float32)
    vals, col, row = [], [], [0]
    for i in range(M):
        for j in np.nonzero(A[i])[0]:
            col.append(int(j)); vals.append(float(A[i, j]))
        row.append(len(col))
    B = rng.uniform(-0.9, 0.9, (K, N)).astype(np.float32)
    x = helper.make_tensor_value_info("B", TensorProto.FLOAT, [K, N])
    y = helper.make_tensor_value_info("C", TensorProto.FLOAT, [M, N])
    v = helper.make_tensor("values", TensorProto.FLOAT, [len(vals)], vals)
    c = helper.make_tensor("col", TensorProto.INT32, [len(col)], col)
    r = helper.make_tensor("rowptr", TensorProto.INT32, [M + 1], row)
    node = helper.make_node("SpmmCsr", ["values", "col", "rowptr", "B"], ["C"])
    return helper.make_model(
        helper.make_graph([node], "s", [x], [y], [v, c, r]),
        opset_imports=[helper.make_opsetid("", 13)])


# ── reference helpers (float32 rounded per operation, matching the kernel) ──
def _fwht_ref(x, n):
    a = [float(v) for v in x]
    length = 1
    while length < n:
        for i in range(0, n, 2 * length):
            for j in range(length):
                u, v = a[i + j], a[i + j + length]
                a[i + j], a[i + j + length] = _f32(u + v), _f32(u - v)
        length <<= 1
    return a


def _conv_ref(feat, wt, batch, H, W, Cin, Cout, K, pad):
    out = []
    for b in range(batch):
        for oc in range(Cout):
            for oh in range(H):
                for ow in range(W):
                    acc = _f32(0.0)
                    for c in range(Cin):
                        for kh in range(K):
                            ih = oh - pad + kh
                            if ih < 0 or ih >= H:
                                continue
                            for kw in range(K):
                                iw = ow - pad + kw
                                if iw < 0 or iw >= W:
                                    continue
                                acc = _f32(acc + _f32(feat[b, ih, iw, c]
                                                      * wt[oc, c, kh, kw]))
                    out.append(_f32(acc))
    return out


def _spmm_ref(M, K, N, vals, col, row, B):
    out = []
    for i in range(M):
        for j in range(N):
            acc = _f32(0.0)
            for p in range(row[i], row[i + 1]):
                acc = _f32(acc + _f32(float(vals[p]) * float(B[col[p]][j])))
            out.append(_f32(acc))
    return out


def _w_int(mem, a, v):
    mem[a:a + 4] = int(v & _MASK).to_bytes(4, "little")


def _w_f32(mem, a, v):
    mem[a:a + 4] = np.float32(v).tobytes()


def _r_f32(mem, a):
    return float(np.frombuffer(bytes(mem[a:a + 4]), dtype="<f4")[0])


# ── FWHT ──────────────────────────────────────────────────────────────────
@pytest.mark.parametrize("n", FWHT, ids=[f"n{n}" for n in FWHT])
def test_stage2_fwht(tmp_path, n):
    asm = _emit(_fwht_model(n), tmp_path)
    rng = np.random.default_rng(0)
    x = [float(v) for v in rng.uniform(-0.9, 0.9, n)]
    mem = bytearray(0x200000)
    inp, out = 0x10000, 0x80000
    for i, v in enumerate(x):
        _w_f32(mem, inp + 4 * i, v)
    _run(asm, {10: inp, 11: out, 12: n}, mem)
    got = [_r_f32(mem, out + 4 * i) for i in range(n)]
    assert np.allclose(got, [float(v) for v in _fwht_ref(x, n)],
                       rtol=1e-4, atol=1e-3)


# ── Conv ──────────────────────────────────────────────────────────────────
@pytest.mark.parametrize("cfg", CONV, ids=[f"c{i}" for i in range(1, 11)])
def test_stage2_conv(tmp_path, cfg):
    batch, H, W, Cin, Cout, K = cfg
    asm = _emit(_conv_model(*cfg), tmp_path)
    pad = K // 2
    rng = np.random.default_rng(0)
    feat = rng.uniform(-0.9, 0.9, (batch, H, W, Cin)).astype(np.float32)
    wt = rng.uniform(-0.9, 0.9, (Cout, Cin, K, K)).astype(np.float32)

    mem = bytearray(0x4000000)
    inp, out = 0x10000, 0x2000000
    off = inp
    for v in [batch, H, W, Cin, Cout, K]:
        _w_int(mem, off, v); off += 4
    for v in feat.reshape(-1):
        _w_f32(mem, off, v); off += 4
    for v in wt.reshape(-1):
        _w_f32(mem, off, v); off += 4

    _run(asm, {10: inp, 11: out, 12: batch * H * W * Cin}, mem)
    got = [_r_f32(mem, out + 4 * i) for i in range(batch * Cout * H * W)]
    ref = _conv_ref(feat, wt, batch, H, W, Cin, Cout, K, pad)
    assert np.allclose(got, [float(v) for v in ref], rtol=1e-4, atol=1e-4)


# ── SpMM ──────────────────────────────────────────────────────────────────
@pytest.mark.parametrize("cfg", SPMM, ids=[f"s{i}" for i in range(1, 11)])
def test_stage2_spmm(tmp_path, cfg):
    M, K, N, dens = cfg
    model = _spmm_model(M, K, N, dens, SPMM.index(cfg) + 1)
    asm = _emit(model, tmp_path)
    from onnx import numpy_helper
    d = {t.name: numpy_helper.to_array(t) for t in model.graph.initializer}
    vals = [float(v) for v in d["values"]]
    col = [int(v) for v in d["col"]]
    row = [int(v) for v in d["rowptr"]]
    nnz = row[-1]
    rng = np.random.default_rng(1)
    B = rng.uniform(-0.9, 0.9, (K, N)).astype(np.float32)

    mem = bytearray(0x4000000)
    inp, out = 0x10000, 0x2000000
    off = inp
    for v in [M, K, N, nnz]:
        _w_int(mem, off, v); off += 4
    for v in row:
        _w_int(mem, off, v); off += 4
    for v in col:
        _w_int(mem, off, v); off += 4
    for v in vals:
        _w_f32(mem, off, v); off += 4
    for v in B.reshape(-1):
        _w_f32(mem, off, v); off += 4

    _run(asm, {10: inp, 11: out, 12: nnz}, mem)
    got = [_r_f32(mem, out + 4 * (i * N + j)) for i in range(M) for j in range(N)]
    ref = _spmm_ref(M, K, N, vals, col, row, B)
    assert np.allclose(got, [float(v) for v in ref], rtol=1e-4, atol=1e-4)
